### PR TITLE
Enhancement issue #113

### PR DESCRIPTION
**Pull request by pautiina**
The code is not finished yet. Please see the code and help finish it.
It's rebase from https://forums.cacti.net/viewtopic.php?f=17&t=52285

### CODE REVIEW

**Comment by pautiina** [comment]
Please, don't merge yet

**Comment by netniV** [comment]
On commit 163ca892024a0f0159d48e3d2951ef8ef45d4fac, you changed Host to Device in some of the messages which is consistent with Cacti.  You have also changed some of the meanings  such as the Down that became Recovering.  Is that because it was wrong?  There is another instance were you've removed Down/Recovering altogether.

On commit 48744c33259e485e6333f07ac7ce3c49522abf10, you have re-enabled logging but you haven't specified a POLLER_VERBOSITY_xxx level so this will always be logged.  Consider adding either MEDIUM or HIGH.  You have also specified 'POLLER' as the section rather than 'THOLD' as the section reporting the information.

**Comment by pautiina** [comment]
I'm thinking, can remove SMS support and leave only support for executing commands with parameter passing to commands?

**Comment by pautiina** [comment]
> You have also changed some of the meanings such as the Down that became Recovering. Is that because it was wrong? There is another instance were you've removed Down/Recovering altogether.

Yes, it's wrong. On next commit I change this.

**Comment by netniV** [comment]
Line 762, which is a comment it would appear, is missing the C from cacti_log plus the POLLER_MEDIUM.  However, if that is because you've moved the log to the later line, you could always remove it (it is source controlled after all 👍 ).

You could remove the SMS part and make it any command.  However, for security reasons, that makes me twitch a little as it would also be as easy to make it run a command it really shouldn't.

Otherwise, looking good.  Shame I don't have an SMS modem spare to test it with 🔓

**Comment by cigamit** [comment]
Please remove the SMS portion (its seems to tie us to a Modem provider when some people may want to use a SMS Gateway) and the Command portion needs to be completely redone to be a selectable dropdown list of commands that are approved and sanitized by an admin.  We don't want users entering a malicious command in there.

**Comment by cigamit** [comment]
What I would prefer to do is to add hooks (yes, plugins can have plug hooks also) so that a separate SMS plugin could be created to add this functionality to Thold.  That was it could be swapped out for other SMS providers or even a completely different alert type / types could be added.  While we are at it, Commands should probably be handled the same way.

**Comment by pautiina** [comment]
> Command portion needs to be completely redone to be a selectable dropdown list of commands that are approved and sanitized by an admin. We don't want users entering a malicious command in the

I do not know how to do it right now.
Everyone has different SMS gateway services and all of them have different api.
Also I would like to add commands that could send out an alert in a viber, telegram or other service.

**Comment by netniV** [comment]
I like the idea of the sub-plugin (as I will call it).  To implement properly, you'd have to create something like:

- Storage of data (such as phone numbers or API keys)
   - generic table with sub-plugin-id, field name, value

      or

   - they create their own fields etc.  

- Basic required fields such as
   - Display Name (ie, Vodafone SMS)
   - a field that holds the string format for the command it uses plus, eg (`/usr/bin/sms -u |username| -p |password| -t |telephone_number|`)

- Functions for
   - Creating default settings
   - Modifying settings per thold
   - Validation of any given settings
   - Validation of any command output as being successful
   - Error Handlers to prevent sub-plugins from causing thold to become disabled.

Once you've done all that, you'd need to create a separate plugin to actually implement the framework and provide the functionality.

**Comment by pautiina** [comment]
@netniV can you finish this job?
I will be very grateful. I think it is useful to many users. Unfortunately I can not completely build the logic of the script and constantly get confusing because of the fact that I work a little with the code Cacti.

**Comment by netniV** [comment]
Oh boy, well probably, though I have thought that alerting methods should really be built into the Cacti Core.  That way there is only one place to setup alerting methods and all plugins would be able to utilise them.

There are other systems I would also like to see integrated, such as Slack etc. and to integrate these requires different strategies.

**Comment by TheWitness** [comment]
@pautiina, you will have to update this pull request as a result of the latest series of commits.  Command execution has handled a bit differently though.  Please review.

**Comment by pautiina** [comment]
> you will have to update this pull request as a result of the latest series of commits. Command execution has handled a bit differently though. Please review.

I know that now I need to update the code, but unfortunately there was no time for me to fully understand the api plugins.

Also, after our communication, it became clear that the code should be more unified and optimized.

Now it’s just pieces of code taken from the old plugin, which was also dorbotan by the community for this functionality.

**Comment by pautiina** [comment]
@TheWitness I see you have implemented command execution functionality.
I close this PR

**Pull request closed without merging**
