### PR TITLE
Add support for upper + lower bytes calculation

### PR DESCRIPTION
**Pull request by manuelm**
Using this data type manipulation allows to calculate the total value
from upper and lower 4 bytes of data. e.g. OID dskAvailLow + dskAvailHigh

See also http://www.muonics.com/Docs/MIBSmithy/UserGuide/commonerrors.php#counter64

### CODE REVIEW

**Comment by TheWitness** [comment]
Old 32bit SNMP implementations force feeding 64bit data.  Yuk.  Let me think about this.

**Comment by manuelm** [comment]
Yup. But it's already widely deployed.

**Comment by TheWitness** [comment]
Yea, I'm with you.

**Comment by TheWitness** [comment]
Well written too dude.

**Comment by TheWitness** [comment]
One thing missing was a README.md update, but I'll handle that one.

**Comment by TheWitness** [comment]
Note that I'm still making changes to the 'develop' branch for the 1.5 release.  So, if you update to test between now and release, if there are additional column changes, you may have to rollback your version to 1.4 in the database and then allow it to re-upgrade:

```sql
UPDATE plugin_config SET version='1.4' WHERE directory='thold';
```

**Pull request merged**
