### PR TITLE
Final fix for Thold 1.0.4 Daemon to address thold processing issues.

### PR DESCRIPTION
**Pull request by ikorzha**
Cigamit, I have worked with my brother developer yesterday and finally produced a fully functional thold daemon for large thold installs that is based on your last development work and commit.. On the bottom of the post please see the statistics before and after enhancements..

The fix addresses the following problems:

Thold Daemon not polling all tholds in large installs.
Tholds being processed once in 2 min vs per minute processing as it should in 1 min polling setup.
Cleanup of "stale" or hung thold processes after 10min mark.
Cleanup of tholds that have PID ID assigned but "hung" over time and never get processed, until PID cleared.

Attached please find a log before the change:
before-log

Attached please find a a log of after patched /includes
final-log

Please let me know if you have any questions with regards to the fix. I am hopeful that you will commit the changes after review as I would like to stay within main "thold" development branch rather than being forked :)

### CODE REVIEW

**Review by cigamit — CHANGES_REQUESTED** [review]
Okay, please make a few changes, and then we can accept this.  Here they are:

1) Don't place the initial opening bracket on a separate line.  We always want the opening bracket on the first line.
2) Same applies to else blocks.  We want the full else on a single line.

I know that this is almost a religious argument, but that is our current coding standard.  Thank your brother for his help.

**Comment by ikorzha** [comment]
My brother re-wrote the code slightly to improve the implementation design. Additionally he did perform code requested re-formatting as per your standard.  Can you please re-examine the pull request and apply it.
I have tested the lastest re-write in my prod system all working same way as previously.
Thank you once again for your consideration.

**Review by cigamit — CHANGES_REQUESTED** [review]
So, we use hard tabs and not soft tabs.  Also, keep the copyright line as it was.  Sorry, but we'll get the right.

There is a  Wiki article on how we want things formatted.

**Comment by ikorzha** [comment]
Cigamit, please re-examine the changes. I think formatting now should be up to specs.
I have tested the latest reformat everything is working as designed.

**Comment by cigamit** [comment]
I'm going to merge this.  However, after the merge, look for some additional changes in format forthcoming.

**Comment by ikorzha** [comment]
Thank you for the merge I have re-tested polling.php after merge all is working as designed. Thank you.

**Pull request merged**
