### PR TITLE
Resolving Issue #160

### PR DESCRIPTION
**Pull request by rojasneva**

### CODE REVIEW

**Comment by netniV** [comment]
Looks good so far. @cigamit will need to weigh in on whether that is likely to cause an issue elsewhere by filtering out so much.

**Comment by cigamit** [comment]
I'm going to roll with this for now.  We can debate a little later on the Aggregate subject.

**Comment by cigamit** [comment]
Taking it back now.  I have to test this completely.  I think it's going to cause some ripple affect for people who create non-templated graph or who create non-templated graphs from external data sources.  Going to take a few days to review.

**Comment by TheWitness** [comment]
This issue is resolved in develop.

**Pull request closed without merging**
