### PR TITLE
Fix php error 

### PR DESCRIPTION
**Pull request by xmacan**
null can be returned here, php 8.x issue - strlen(): Passing null to parameter #1 ($string)

### CODE REVIEW

**Review by TheWitness — CHANGES_REQUESTED** [review]
Better use `$email != ''`

**Review by TheWitness — CHANGES_REQUESTED** [review]
Also, changing emails from string to array seems odd.  So, the $emails array should have another name and the compare should be !=>

**Comment by TheWitness** [comment]
Lastly using `count()` is dangerous.  I prefer `cacti_sizeof()`.

**Comment by xmacan** [comment]
ok, better fix

**Review by TheWitness — APPROVED** [review]

**Pull request merged**
